name: CI
on:

  #Trigger bestämmer när workflowen ska starta
  #kan innehåller pull requests
  # När någon skickar upp ny kod startar pipeline automatiskt.
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CUSTOMER_SERVICE: http://customer-service:8081

    steps:
      # github hämtar ner projekts kod till virtuella miljö där pipeline  körs.
      - name: Checkout code
        uses: actions/checkout@v3
      # för att projekt byggas i java rätt version
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Check variable
        run: echo "CUSTOMER_SERVICE=$CUSTOMER_SERVICE"
      #projekt byggs med Gradle
      #kontrollerar att koden kompilerar korrekt.
      - name: Build and test
        run: ./gradlew clean test
